import React from 'react';
import ReactDOM from 'react-dom';

// in this file we have created list and we are giving styling to it.
// for styling wr are using attributes and properties
// first we have created a stylesheet "index-style.css" in public folder and added class "color" in it
// then we included that css file in "index.html" in head tag

var wantToEdit = false;

// if we want to use an image in webpage then we can store url in variable and pass it to img tag
var url = "https://picsum.photos/200";

// here we arecreating an json object for inline styling
const state = {
  color:'yellow',
  backgroundColor:'black'
};

ReactDOM.render(
  <div>
    <h1 className = 'color' contentEditable = {wantToEdit}>Favourite Food List</h1>
    {/* contentEditable attribute takes true or false value
        if its true then we can edit content on webpage else we cant edit
        so we have stored this true or false value in wantToEdit variable and used it here
    */}
    <img src = {url} alt="this is random image generated by lorem picsum"/>
    <ul>
      {/* inline styling */}
      <li style={{color:"blue"}}>Pizza</li>
      {/* another way of inline styling is using json objects*/}
      <li style={state}>Burger</li>
      <li>Cold-Coffee</li>
    </ul>
  </div>,document.getElementById('root')
);